services:
  server:
    build: ./server
    container_name: qr-server
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: qr-frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
