apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |
    {
      "api": "http://192.168.49.2:31201"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: Never
          env:
            - name: VITE_BACKEND_API_URL
              value: http://192.168.49.2:31201
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-volume
              mountPath: /app/dist/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
